"""
Generate requirements-ci.txt = requirements.txt minus the ML runtime.

    cd backend && python scripts/make_ci_requirements.py            # rewrite the file
    cd backend && python scripts/make_ci_requirements.py --check    # exit 1 if it is stale

CI installs the light set (about 0.6 GB, two minutes) instead of the full image (about 11 GB).
Deriving it by subtraction keeps one source of truth: pin a version in requirements.txt,
re-run this, and CI follows. tests/test_ci_requirements.py fails when the two drift.
"""
from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "requirements.txt")
OUT = os.path.join(HERE, "requirements-ci.txt")

# The ML runtime: what the tests marked `needs_ml` require. ~2.5 GB of wheels.
HEAVY = ("torch", "torchvision", "faiss-cpu", "sentence-transformers", "easyocr")

HEADER = [
    "# CI / lightweight test dependencies: requirements.txt minus the ML runtime",
    "# (" + ", ".join(HEAVY) + ").",
    "# GENERATED by scripts/make_ci_requirements.py - edit requirements.txt, then re-run it.",
    "# Tests that need the ML runtime are marked `needs_ml` and are skipped, visibly, without it.",
    "",
]


def package_name(line: str) -> str:
    return re.split(r"[=<>!~\[\s;]", line.strip(), maxsplit=1)[0].lower().replace("_", "-")


def render(source_text: str) -> str:
    lines = list(HEADER)
    for raw in source_text.splitlines():
        t = raw.split("#", 1)[0].strip()          # drop trailing comments
        if not t or t.startswith("--"):           # blank, comment-only, or pip option (the torch index)
            continue
        if package_name(t) in HEAVY:
            continue
        lines.append(t)
    return "\n".join(lines) + "\n"


def main() -> int:
    with open(SRC, encoding="utf-8") as f:
        wanted = render(f.read())
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != wanted:
            print("requirements-ci.txt is stale: run `python scripts/make_ci_requirements.py`")
            return 1
        print("requirements-ci.txt is up to date")
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(wanted)
    print(f"wrote {OUT} ({sum(1 for l in wanted.splitlines() if l and not l.startswith('#'))} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
